
Conversation opened 1 read message.

Skip to content
Using Gmail with screen readers
Search



Gmail
COMPOSE
Labels
Inbox (131)
Starred
Sent Mail
Drafts (83)
Categories
Junk
More 
Hangouts

 
 
  More 
3 of 989  
 
Print all In new window
Fwd: Agricultural Database 
Inbox
x 

Navya shree
Attachments9:35 AM (21 minutes ago)

to me 
---------- Forwarded message ----------
From: "Preethi N Gowda" <preethingowda65@gmail.com>
Date: Dec 17, 2017 8:18 PM
Subject: Agricultural Database
To: <nandini.s.dayanand@gmail.com>
Cc:
Attachments area
	
Click here to Reply or Forward
10.3 GB (68%) of 15 GB used
Manage
Terms - Privacy
Last account activity: 0 minutes ago
Details


#include<iostream.h>
main()
{
int crop;
cout<<"1.Sugarcane\n2.Paddy\n3.Coffee\n4.Raagi\n";
cout<<"Select any one\n";
cin>>crop;
if(crop==1)
cout<<"Soil:diverse\nTemperature:25-32C\nSeason:Spring\npH:5-8.5\nFertiliser:Vermicompost\n";
else if(crop=2)
cout<<"Soil:Alluvial\nTemperature:20-27C\nSeason:June\npH:5.5-7\nFertiliser:NPK\n";
else if(crop==3)
cout<<"Soil:Well-aerated\nTemperature:20-27C\nSeason:Rainy\npH:5.2-6.3\nFertliser:Mycorrhizae\n";
else if(crop==4)
cout<<"Soil:Porous\nTemperature:25-33C\nSeason:June\npH:4.7-7.5\nFertiliser:Azospirillum\n";
else
cout<<"crop not found\n";
return 0;
}
DATABASE.CPP
Open with
Displaying DATABASE.CPP.